apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter
        args: 
        - "--log.level=debug"
        - "--config.file=/etc/blackbox_exporter/blackbox.yml"
        ports:
        - containerPort: 9115
        volumeMounts:
        - name: config-volume
          mountPath: /etc/blackbox_exporter/blackbox.yml
          subPath: blackbox.yml
      volumes:
      - name: config-volume
        configMap:
          name: blackbox-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
spec:
  selector:
    app: blackbox
  ports:
    - port: 9115
      targetPort: 9115
